<!DOCTYPE html><html lang="en">
<!-- Mirrored from overiq.com/python-101/exception-handling-in-python/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 01 Feb 2025 11:09:02 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head><meta charset="utf-8"/>
<script>var __ezHttpConsent={setByCat:function(src,tagType,attributes,category,force){var setScript=function(){if(force||window.ezTcfConsent[category]){var scriptElement=document.createElement(tagType);scriptElement.src=src;attributes.forEach(function(attr){for(var key in attr){if(attr.hasOwnProperty(key)){scriptElement.setAttribute(key,attr[key]);}}});var firstScript=document.getElementsByTagName(tagType)[0];firstScript.parentNode.insertBefore(scriptElement,firstScript);}};if(force||(window.ezTcfConsent&&window.ezTcfConsent.loaded)){setScript();}else if(typeof getEzConsentData==="function"){getEzConsentData().then(function(ezTcfConsent){if(ezTcfConsent&&ezTcfConsent.loaded){setScript();}else{console.error("cannot get ez consent data");force=true;setScript();}});}else{force=true;setScript();console.error("getEzConsentData is not a function");}},};</script>
<script>var ezTcfConsent=window.ezTcfConsent?window.ezTcfConsent:{loaded:false,store_info:false,develop_and_improve_services:false,measure_ad_performance:false,measure_content_performance:false,select_basic_ads:false,create_ad_profile:false,select_personalized_ads:false,create_content_profile:false,select_personalized_content:false,understand_audiences:false,use_limited_data_to_select_content:false,};function getEzConsentData(){return new Promise(function(resolve){document.addEventListener("ezConsentEvent",function(event){var ezTcfConsent=event.detail.ezTcfConsent;resolve(ezTcfConsent);});});}</script>
<script>if(typeof _setEzCookies!=='function'){function _setEzCookies(ezConsentData){var cookies=window.ezCookieQueue;for(var i=0;i<cookies.length;i++){var cookie=cookies[i];if(ezConsentData&&ezConsentData.loaded&&ezConsentData[cookie.tcfCategory]){document.cookie=cookie.name+"="+cookie.value;}}}}
window.ezCookieQueue=window.ezCookieQueue||[];if(typeof addEzCookies!=='function'){function addEzCookies(arr){window.ezCookieQueue=[...window.ezCookieQueue,...arr];}}
addEzCookies([]);if(window.ezTcfConsent&&window.ezTcfConsent.loaded){_setEzCookies(window.ezTcfConsent);}else if(typeof getEzConsentData==="function"){getEzConsentData().then(function(ezTcfConsent){if(ezTcfConsent&&ezTcfConsent.loaded){_setEzCookies(window.ezTcfConsent);}else{console.error("cannot get ez consent data");_setEzCookies(window.ezTcfConsent);}});}else{console.error("getEzConsentData is not a function");_setEzCookies(window.ezTcfConsent);}</script>
<script data-ezscrex='false' data-cfasync='false' data-pagespeed-no-defer>var __ez=__ez||{};__ez.stms=Date.now();__ez.evt={};__ez.script={};__ez.ck=__ez.ck||{};__ez.template={};__ez.template.isOrig=true;window.__ezScriptHost="//www.ezojs.com";__ez.queue=__ez.queue||function(){var e=0,i=0,t=[],n=!1,o=[],r=[],s=!0,a=function(e,i,n,o,r,s,a){var l=arguments.length>7&&void 0!==arguments[7]?arguments[7]:window,d=this;this.name=e,this.funcName=i,this.parameters=null===n?null:w(n)?n:[n],this.isBlock=o,this.blockedBy=r,this.deleteWhenComplete=s,this.isError=!1,this.isComplete=!1,this.isInitialized=!1,this.proceedIfError=a,this.fWindow=l,this.isTimeDelay=!1,this.process=function(){f("... func = "+e),d.isInitialized=!0,d.isComplete=!0,f("... func.apply: "+e);var i=d.funcName.split("."),n=null,o=this.fWindow||window;i.length>3||(n=3===i.length?o[i[0]][i[1]][i[2]]:2===i.length?o[i[0]][i[1]]:o[d.funcName]),null!=n&&n.apply(null,this.parameters),!0===d.deleteWhenComplete&&delete t[e],!0===d.isBlock&&(f("----- F'D: "+d.name),m())}},l=function(e,i,t,n,o,r,s){var a=arguments.length>7&&void 0!==arguments[7]?arguments[7]:window,l=this;this.name=e,this.path=i,this.async=o,this.defer=r,this.isBlock=t,this.blockedBy=n,this.isInitialized=!1,this.isError=!1,this.isComplete=!1,this.proceedIfError=s,this.fWindow=a,this.isTimeDelay=!1,this.isPath=function(e){return"/"===e[0]&&"/"!==e[1]},this.getSrc=function(e){return void 0!==window.__ezScriptHost&&this.isPath(e)&&"banger.js"!==this.name?window.__ezScriptHost+e:e},this.process=function(){l.isInitialized=!0,f("... file = "+e);var i=this.fWindow?this.fWindow.document:document,t=i.createElement("script");t.src=this.getSrc(this.path),!0===o?t.async=!0:!0===r&&(t.defer=!0),t.onerror=function(){var e={url:window.location.href,name:l.name,path:l.path,user_agent:window.navigator.userAgent};"undefined"!=typeof _ezaq&&(e.pageview_id=_ezaq.page_view_id);var i=encodeURIComponent(JSON.stringify(e)),t=new XMLHttpRequest;t.open("GET/index.html","//g.ezoic.net/ezqlog?d="+i,!0),t.send(),f("----- ERR'D: "+l.name),l.isError=!0,!0===l.isBlock&&m()},t.onreadystatechange=t.onload=function(){var e=t.readyState;f("----- F'D: "+l.name),e&&!/loaded|complete/.test(e)||(l.isComplete=!0,!0===l.isBlock&&m())},i.getElementsByTagName("head")[0].appendChild(t)}},d=function(e,i){this.name=e,this.path="",this.async=!1,this.defer=!1,this.isBlock=!1,this.blockedBy=[],this.isInitialized=!0,this.isError=!1,this.isComplete=i,this.proceedIfError=!1,this.isTimeDelay=!1,this.process=function(){}};function c(e,i,n,s,a,d,c,u,f){var m=new l(e,i,n,s,a,d,c,f);!0===u?o[e]=m:r[e]=m,t[e]=m,h(m)}function h(e){!0!==u(e)&&0!=s&&e.process()}function u(e){if(!0===e.isTimeDelay&&!1===n)return f(e.name+" blocked = TIME DELAY!"),!0;if(w(e.blockedBy))for(var i=0;i<e.blockedBy.length;i++){var o=e.blockedBy[i];if(!1===t.hasOwnProperty(o))return f(e.name+" blocked = "+o),!0;if(!0===e.proceedIfError&&!0===t[o].isError)return!1;if(!1===t[o].isComplete)return f(e.name+" blocked = "+o),!0}return!1}function f(e){var i=window.location.href,t=new RegExp("[?&]ezq=([^&#]*)","i").exec(i);"1"===(t?t[1]:null)&&console.debug(e)}function m(){++e>200||(f("let's go"),p(o),p(r))}function p(e){for(var i in e)if(!1!==e.hasOwnProperty(i)){var t=e[i];!0===t.isComplete||u(t)||!0===t.isInitialized||!0===t.isError?!0===t.isError?f(t.name+": error"):!0===t.isComplete?f(t.name+": complete already"):!0===t.isInitialized&&f(t.name+": initialized already"):t.process()}}function w(e){return"[object Array]"==Object.prototype.toString.call(e)}return window.addEventListener("load",(function(){setTimeout((function(){n=!0,f("TDELAY -----"),m()}),5e3)}),!1),{addFile:c,addFileOnce:function(e,i,n,o,r,s,a,l,d){t[e]||c(e,i,n,o,r,s,a,l,d)},addDelayFile:function(e,i){var n=new l(e,i,!1,[],!1,!1,!0);n.isTimeDelay=!0,f(e+" ...  FILE! TDELAY"),r[e]=n,t[e]=n,h(n)},addFunc:function(e,n,s,l,d,c,u,f,m,p){!0===c&&(e=e+"_"+i++);var w=new a(e,n,s,l,d,u,f,p);!0===m?o[e]=w:r[e]=w,t[e]=w,h(w)},addDelayFunc:function(e,i,n){var o=new a(e,i,n,!1,[],!0,!0);o.isTimeDelay=!0,f(e+" ...  FUNCTION! TDELAY"),r[e]=o,t[e]=o,h(o)},items:t,processAll:m,setallowLoad:function(e){s=e},markLoaded:function(e){if(e&&0!==e.length){if(e in t){var i=t[e];!0===i.isComplete?f(i.name+" "+e+": error loaded duplicate"):(i.isComplete=!0,i.isInitialized=!0)}else t[e]=new d(e,!0);f("markLoaded dummyfile: "+t[e].name)}},logWhatsBlocked:function(){for(var e in t)!1!==t.hasOwnProperty(e)&&u(t[e])}}}();__ez.evt.add=function(e,t,n){e.addEventListener?e.addEventListener(t,n,!1):e.attachEvent?e.attachEvent("on"+t,n):e["on"+t]=n()},__ez.evt.remove=function(e,t,n){e.removeEventListener?e.removeEventListener(t,n,!1):e.detachEvent?e.detachEvent("on"+t,n):delete e["on"+t]};__ez.script.add=function(e){var t=document.createElement("script");t.src=e,t.async=!0,t.type="text/javascript",document.getElementsByTagName("head")[0].appendChild(t)};__ez.dot={};__ez.queue.addFile('../../detroitchicago/boise.js', '../../detroitchicago/boisebb26.js?gcb=195-3&amp;cb=5', true, [], true, false, true, false);__ez.queue.addFile('../../parsonsmaize/abilene.js', '../../parsonsmaize/abilenec0f9.js?gcb=195-3&amp;cb=7f81d60744', true, [], true, false, true, false);__ez.queue.addFile('../../parsonsmaize/mulvane.js', '../../parsonsmaize/mulvane2d63.js?gcb=195-3&amp;cb=e75e48eec0', true, ['/parsonsmaize/abilene.js'], true, false, true, false);__ez.queue.addFile('../../detroitchicago/birmingham.js', '../../detroitchicago/birminghame7ec.js?gcb=195-3&amp;cb=539c47377c', true, ['/parsonsmaize/abilene.js'], true, false, true, false);</script>
<script data-ezscrex="false" type="text/javascript" data-cfasync="false">window._ezaq = Object.assign({"ad_cache_level":1,"adpicker_placement_cnt":0,"ai_placeholder_cache_level":1,"ai_placeholder_placement_cnt":-1,"domain_id":92771,"ezcache_level":1,"ezcache_skip_code":0,"has_bad_image":0,"has_bad_words":0,"is_sitespeed":0,"lt_cache_level":0,"response_size":81757,"response_size_orig":75989,"response_time_orig":401,"template_id":5,"url":"https://overiq.com/python-101/exception-handling-in-python/","word_count":0,"worst_bad_word_level":0}, typeof window._ezaq !== "undefined" ? window._ezaq : {});__ez.queue.markLoaded('ezaqBaseReady');</script>
<script type='text/javascript' data-ezscrex='false' data-cfasync='false'>
window.ezAnalyticsStatic = true;

function analyticsAddScript(script) {
	var ezDynamic = document.createElement('script');
	ezDynamic.type = 'text/javascript';
	ezDynamic.innerHTML = script;
	document.head.appendChild(ezDynamic);
}
function getCookiesWithPrefix() {
    var allCookies = document.cookie.split(';');
    var cookiesWithPrefix = {};

    for (var i = 0; i < allCookies.length; i++) {
        var cookie = allCookies[i].trim();

        for (var j = 0; j < arguments.length; j++) {
            var prefix = arguments[j];
            if (cookie.indexOf(prefix) === 0) {
                var cookieParts = cookie.split('=');
                var cookieName = cookieParts[0];
                var cookieValue = cookieParts.slice(1).join('=');
                cookiesWithPrefix[cookieName] = decodeURIComponent(cookieValue);
                break; // Once matched, no need to check other prefixes
            }
        }
    }

    return cookiesWithPrefix;
}
function productAnalytics() {
	var d = {"pr":[6],"omd5":"a6ec0868b789f038373a5be3bcfd32a6"};
	d.u = _ezaq.url;
	d.p = _ezaq.page_view_id;
	d.v = _ezaq.visit_uuid;
	d.ab = _ezaq.ab_test_id;
	d.e = JSON.stringify(_ezaq);
	d.ref = document.referrer;
	d.c = getCookiesWithPrefix('active_template', 'ez', 'lp_');
	if(typeof ez_utmParams !== 'undefined') {
		d.utm = ez_utmParams;
	}

	var dataText = JSON.stringify(d);
	var xhr = new XMLHttpRequest();
	xhr.open('POST/index.html','/ezais/analytics?cb=1', true);
	xhr.onload = function () {
		if (xhr.status!=200) {
            return;
		}

        if(document.readyState !== 'loading') {
            analyticsAddScript(xhr.response);
            return;
        }

        var eventFunc = function() {
            if(document.readyState === 'loading') {
                return;
            }
            document.removeEventListener('readystatechange', eventFunc, false);
            analyticsAddScript(xhr.response);
        };

        document.addEventListener('readystatechange', eventFunc, false);
	};
	xhr.setRequestHeader('Content-Type','text/plain');
	xhr.send(dataText);
}
__ez.queue.addFunc("productAnalytics", "productAnalytics", null, true, ['ezaqBaseReady'], false, false, false, true);
</script><base />
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <title>Exception Handling in Python - Python Tutorial - OverIQ.com</title>

    
    



    <meta name="description" content="Exception handling is a mechanism which allows us to handle errors gracefully while the program is running instead of abruptly ending the program exe…"/>



    <link rel="canonical" href="index.html"/>


<meta property="og:locale" content="en_US"/>
<meta property="og:type" content="article"/>
<meta property="og:title" content="Exception Handling in Python"/>

    <meta property="og:description" content="Exception handling is a mechanism which allows us to handle errors gracefully while the program is running instead of abruptly ending the program exe…"/>


<meta property="og:url" content="https://overiq.com/python-101/exception-handling-in-python/"/>
<meta property="og:site_name" content="OverIQ.com"/>


<meta property="article:publisher" content="https://www.facebook.com/OverIQ/"/>



<meta name="twitter:card" content="summary_large_image"/>

    <meta name="twitter:description" content="Exception handling is a mechanism which allows us to handle errors gracefully while the program is running instead of abruptly ending the program exe…"/>


<meta name="twitter:title" content="Exception Handling in Python"/>
<meta name="twitter:site" content="@infoOverIQ"/>

<meta name="twitter:creator" content="@infoOverIQ"/>




    
    
    


    
    
    


    <link rel="alternate" type="application/rss+xml" title="RSS" href="../../feed.xml/index.html"/>
    
    
    <link href="../../../fonts.googleapis.com/cssd2d5.css?family=Open+Sans" rel="stylesheet"/>
    <link rel="stylesheet" href="../../../maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="icon" href="../../static/wiki/favicon.png" sizes="32x32"/>

    <link rel="stylesheet" href="../../static/CACHE/css/output.db46da465a8b.css" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-125424793-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-125424793-1');
    </script>


<script type='text/javascript'>
var ezoTemplate = 'orig_site';
var ezouid = '1';
var ezoFormfactor = '1';
</script><script data-ezscrex="false" type='text/javascript'>
var soc_app_id = '0';
var did = 92771;
var ezdomain = 'overiq.com';
var ezoicSearchable = 1;
</script></head>
<body>

<div class="overiq-header text-center">
    <div class="site-branding">
        <p class="main-title">
            <a href="../../index.html" rel="home">
                OverIQ.com
            </a>
        </p>
    </div>
</div>

<!-- Navigation -->
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../../index.html">Home</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                

                <li>
                    <a href="../../blog/index.html">Blog</a>
                </li>
                <li>
                    <a href="../../contact/index.html">Contact</a>
                </li>
                <li>
                    <a href="../../about/index.html">About</a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right visible-lg visible-md">
                <li>
                    <a href="../../feed.xml/index.html" title="RSS" target="_blank">
                        <i class="fa fa-rss fa-lg" aria-hidden="true"></i>
                    </a>
                </li>
                <li>
                    <a href="https://github.com/overiq/" target="_blank" title="Github">
                        <i class="fa fa-github fa-lg" aria-hidden="true"></i>
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/OverIQ/" target="_blank" title="Facebook">
                        <i class="fa fa-facebook fa-lg" aria-hidden="true"></i>
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/infoOverIQ" target="_blank" title="Twitter">
                        <i class="fa fa-twitter fa-lg" aria-hidden="true"></i>
                    </a>
                </li>

                

            </ul>

            <form action="https://overiq.com/search/" class="navbar-form navbar-left" role="search">

                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" name="query" value=""/>
                </div>

                <button type="submit" class="btn btn-default">Submit</button>
            </form>

        </div>



        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<div class="container">

    


    <div class="se-pre-con"></div>

    

    <div class="row">

        
        <div class="main">
            <div class="col-lg-8 col-md-8 col-sm-12">
                

    


    
        <ol class="breadcrumb">

    <li><a href="../../index.html">Home</a></li>

    
        
        <li><a href="../index.html">Python Tutorial</a></li>
        

        

        
    
        

        

        
            <li class="active">Exception Handling in Python</li>
        
    

</ol>
    


<h1>Exception Handling in Python</h1>




    <p><i class="fa fa-calendar" aria-hidden="true"></i>
        Last updated on September 22, 2020
    </p>


<hr/>



<p>Exception handling is a mechanism which allows us to handle errors gracefully while the program is running instead of abruptly ending the program execution.</p>
<span id="runtime-errors" class="anchor-target"></span><h2 class="heading">Runtime Errors <a class="header-link" href="#runtime-errors">#</a></h2>

<p>Runtime errors are the errors which happens while the program is running. Note is that runtime errors do not indicate there is a problem in the structure (or syntax) of the program. When runtime errors occurs Python interpreter perfectly understands your statement but it just can&#39;t execute it. However, Syntax Errors occurs due to incorrect structure of the program. Both type of errors halts the execution of the program as soon as they are encountered and displays an error message (or traceback) explaining the probable cause of the problem.</p>

<p>The following are some examples of runtime errors.</p>

<p><strong>Example 1</strong>: Division by a zero.</p>
<div class="codeblock language-pycon"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="go">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="mi">2</span><span class="o">/</span><span class="mi">0</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&#34;&lt;stdin&gt;&#34;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">division by zero</span>
<span class="go">&gt;&gt;&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/Qk7/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>Example 2</strong>: Adding string to an integer.</p>
<div class="codeblock language-pycon"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="go">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="mi">10</span> <span class="o">+</span> <span class="s2">&#34;12&#34;</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&#34;&lt;stdin&gt;&#34;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for +: &#39;int&#39; and &#39;str&#39;</span>
<span class="go">&gt;&gt;&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/RlL/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>Example 3</strong>: Trying to access element at invalid index.</p>
<div class="codeblock language-pycon"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7
8</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="go">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">list1</span> <span class="o">=</span> <span class="p">[</span><span class="mi">11</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">99</span><span class="p">,</span> <span class="mi">15</span><span class="p">]</span>
<span class="go">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">list1</span><span class="p">[</span><span class="mi">10</span><span class="p">]</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&#34;&lt;stdin&gt;&#34;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">IndexError</span>: <span class="n">list index out of range</span>
<span class="go">&gt;&gt;&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/Vv5/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>Example 4</strong>: Opening a file in read mode which doesn&#39;t exist.</p>
<div class="codeblock language-pycon"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="go">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s2">&#34;filedoesntexists.txt&#34;</span><span class="p">,</span> <span class="s2">&#34;r&#34;</span><span class="p">)</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&#34;&lt;stdin&gt;&#34;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
<span class="gr">FileNotFoundError</span>: <span class="n">[Errno 2] No such file or directory: &#39;filedoesntexists.txt&#39;</span>
<span class="go">&gt;&gt;&gt;</span>
<span class="go">&gt;&gt;&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/WPW/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p>Again note that all the above statements are syntactically valid, the only problem is that when Python tries to execute them, they got into an invalid state.</p>

<p>An error which occur while the program is running is known as an exception. When this happens, we say Python has raised an exception or an exception is thrown. Whenever such errors happen, Python creates a special type of object which contains all the relevant information about the error just occurred. For example, it contains a line number at which the error occurred, error messages (remember it is called traceback) and so on. By default, these errors simply halts the execution of the program. Exception handling mechanism allows us to deal with such errors gracefully without halting the program.</p>
<span id="try-except-statement" class="anchor-target"></span><h2 class="heading">try-except statement <a class="header-link" href="#try-except-statement">#</a></h2>

<p>In Python, we use <code>try-except</code> statement for exception handling. Its syntax is as follows:</p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7
8
9</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="c1"># try block</span>
    <span class="c1"># write code that might raise an exception here</span>
    <span class="o">&lt;</span><span class="n">statement_1</span><span class="o">&gt;</span>
    <span class="o">&lt;</span><span class="n">statement_2</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="n">ExceptiomType</span><span class="p">:</span>
    <span class="c1"># except block</span>
    <span class="c1"># handle exception here</span>
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p>The code begins with the word <code>try</code>, which is a reserved keyword, followed by a colon (<code>:</code>). In the next line we have try block. The try block contains code that might raise an exception. After that, we have an <code>except</code> clause that starts with the word <code>except</code>, which is again a reserved keyword, followed by an exception type and a colon (<code>:</code>). In the next line, we have an except block. The except block contains code to handle the exception. As usual, code inside the try and except block must be properly indented, otherwise, you will get an error.</p>

<p>Here is how the <code>try-except</code> statement executes:</p>

<p>When an exception occurs in the try block, the execution of the rest of the statements in the try block is skipped. If the exception raised matches the exception type in the <code>except</code> clause, the corresponding handler is executed.</p>

<p>If the exception raised in the try block doesn&#39;t matches with the exception type specified in the <code>except</code> clause the program halts with a traceback.</p>

<p>On the other hand, If no exception is raised in the try block, the except <code>clause</code> is skipped.</p>

<p>Let&#39;s take an example:</p>

<p><strong>python101/Chapter-19/exception_handling.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7
8</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">num</span> <span class="o">=</span>  <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;Enter a number: &#34;</span><span class="p">))</span>
    <span class="n">result</span> <span class="o">=</span> <span class="mi">10</span><span class="o">/</span><span class="n">num</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Result: &#34;</span><span class="p">,</span> <span class="n">result</span><span class="p">)</span>    

<span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Exception Handler for ZeroDivisionError&#34;</span><span class="p">)</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;We cant divide a number by 0&#34;</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/XQk/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p>Run the program and enter 0.</p>

<p><strong>First run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter a number: 0
Exception Handler for ZeroDivisionError
We cant divide a number by 0
</pre></div>
</td></tr></tbody></table></div>
<p>In this example, the try block in line 3 raises a <code>ZeroDivisionError</code>. When an exception occurs Python looks for the <code>except</code> clause with the matching exception type. In this case, it finds one and runs the exception handler code in that block. Notice that because an exception is raised in line 3, the execution of reset of the statements in the try block is skipped.</p>

<p>Run the program again but this time enter a string instead of a number:</p>

<p><strong>Second run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter a number: str
Traceback (most recent call last):
  File &#34;exception_example.py&#34;, line 2, in &lt;module&gt;
    num = int(input(&#34;Enter a number: &#34;))
ValueError: invalid literal for int() with base 10: &#39;str&#39;
</pre></div>
</td></tr></tbody></table></div>
<p>This time our program crashes with the <code>ValueError</code> exception. The problem is that the built-in <code>int()</code> only works with strings that contain numbers only, if you pass a string containing non-numeric character it will throw a <code>ValueError</code> exception.</p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7
8
9</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="o">&gt;&gt;&gt;</span>
<span class="o">&gt;&gt;&gt;</span> <span class="nb">int</span><span class="p">(</span><span class="s2">&#34;123&#34;</span><span class="p">)</span>              <span class="o">//</span> <span class="n">that</span><span class="s1">&#39;s fine because string only contains numbers</span>
<span class="mi">123</span>
<span class="o">&gt;&gt;&gt;</span>
<span class="o">&gt;&gt;&gt;</span> <span class="nb">int</span><span class="p">(</span><span class="s2">&#34;str&#34;</span><span class="p">)</span>              <span class="o">//</span> <span class="n">error</span> <span class="n">can</span><span class="s1">&#39;t converts characters to numbers</span>
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">&#34;&lt;stdin&gt;&#34;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="ne">ValueError</span><span class="p">:</span> <span class="n">invalid</span> <span class="n">literal</span> <span class="k">for</span> <span class="nb">int</span><span class="p">()</span> <span class="k">with</span> <span class="n">base</span> <span class="mi">10</span><span class="p">:</span> <span class="s1">&#39;str&#39;</span>
<span class="o">&gt;&gt;&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p>As we have don&#39;t have an <code>except</code> clause with the <code>ValueError</code> exception, our program crashes with <code>ValueError</code> exception.</p>

<p>Run the program again and this time enter an integer other than <code>0</code>.</p>

<p><strong>Third run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter a number: 4
Result:  2.5
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/Y70/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p>In this case, statements in the try block executes without throwing any exception, as a result, the <code>except</code> clause is skipped.</p>
<span id="handling-multiple-exceptions" class="anchor-target"></span><h2 class="heading">Handling Multiple Exceptions <a class="header-link" href="#handling-multiple-exceptions">#</a></h2>

<p>We can add as many <code>except</code> clause as we want to handle different types of exceptions. The general format of such a <code>try-except</code> statement is as follows:</p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="c1"># try block</span>
    <span class="c1"># write code that might raise an exception here</span>
    <span class="o">&lt;</span><span class="n">statement_1</span><span class="o">&gt;</span>
    <span class="o">&lt;</span><span class="n">statement_2</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="o">&lt;</span><span class="n">ExceptiomType1</span><span class="o">&gt;</span><span class="p">:</span>
    <span class="c1"># except block</span>
    <span class="c1"># handle ExceptiomType1 here</span>
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="o">&lt;</span><span class="n">ExceptiomType2</span><span class="o">&gt;</span><span class="p">:</span>
    <span class="c1"># except block</span>
    <span class="c1"># handle ExceptiomType2 here</span>
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="o">&lt;</span><span class="n">ExceptiomType2</span><span class="o">&gt;</span><span class="p">:</span>
    <span class="c1"># except block</span>
    <span class="c1"># handle ExceptiomType3 here</span>
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
<span class="k">except</span><span class="p">:</span>
    <span class="c1"># handle any type of exception here</span>
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p>Here is how it works:</p>

<p>When an exception occurs, Python matches the exception raised against every <code>except</code> clause sequentially. If a match is found then the handler in the corresponding <code>except</code> clause is executed and rest of the <code>except</code> clauses are skipped. </p>

<p>In case the exception raised doesn&#39;t matches any <code>except</code> clause before the last <code>except</code> clause (line 18), then the handler in the last <code>except</code> clause is executed. Note that the last <code>except</code> clause doesn&#39;t have any exception type in front of it, as a result, it can catch any type of exception. Of course, this last <code>except</code> clause is entirely optional but we commonly use it as a last resort to catch the unexpected errors and thus prevent the program from crashing.</p>

<p>The following program demonstrates how to use multiple <code>except</code> clauses.</p>

<p><strong>python101/Chapter-19/handling_muliple_types_of_exceptions.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">num1</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;Enter a num1: &#34;</span><span class="p">))</span>
    <span class="n">num2</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;Enter a num2: &#34;</span><span class="p">))</span>

    <span class="n">result</span> <span class="o">=</span> <span class="n">num1</span> <span class="o">/</span> <span class="n">num2</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Result: &#34;</span><span class="p">,</span> <span class="n">result</span><span class="p">)</span>

<span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;</span><span class="se">\n</span><span class="s2">Exception Handler for ZeroDivisionError&#34;</span><span class="p">)</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;We cant divide a number by 0&#34;</span><span class="p">)</span>

<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;</span><span class="se">\n</span><span class="s2">Exception Handler for ValueError&#34;</span><span class="p">)</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Invalid input: Only integers are allowed&#34;</span><span class="p">)</span>

<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;</span><span class="se">\n</span><span class="s2">Some unexpected error occurred&#34;</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/Z8v/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>First run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter a num1: 10
Enter a num2: 0

Exception Handler for ZeroDivisionError
We cant divide a number by 0
</pre></div>
</td></tr></tbody></table></div>
<p><strong>Second run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter a num1: 100
Enter a num2: a13

Exception Handler for ValueError
Invalid input: Only integers are allowed
</pre></div>
</td></tr></tbody></table></div>
<p><strong>Third run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter a num1: 5000
Enter a num2: 2
Result:  2500
</pre></div>
</td></tr></tbody></table></div>
<p>Here is another example program that asks the user to enter the filename and then prints the content of the file to the console.</p>

<p><strong>python101/Chapter-19/exception_handling_while_reading_file.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="n">filename</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">&#34;Enter file name: &#34;</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="n">filename</span><span class="p">,</span> <span class="s2">&#34;r&#34;</span><span class="p">)</span>

    <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">f</span><span class="p">:</span>
        <span class="k">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="s2">&#34;&#34;</span><span class="p">)</span>

    <span class="n">f</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>

<span class="k">except</span> <span class="n">FileNotFoundError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;File not found&#34;</span><span class="p">)</span>

<span class="k">except</span> <span class="n">PermissionError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;You don&#39;t have the permission to read the file&#34;</span><span class="p">)</span>

<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Unexpected error while reading the file&#34;</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/163/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p>Run the program and specify a file that doesn&#39;t exist.</p>

<p><strong>First run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter file name: file_doesnt_exists.md
File not found
</pre></div>
</td></tr></tbody></table></div>
<p>Run the program again and this time specify a file that you don&#39;t have permission to read.</p>

<p><strong>Second run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter file name: /etc/passwd
You don&#39;t have the permission to read the file
</pre></div>
</td></tr></tbody></table></div>
<p>Run the program once more but this time specify a file that does exist and you have the permission to read it.</p>

<p><strong>Third run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter file name: ../Chapter-18/readme.md
First Line
Second Line
Third Line
Fourth Line
Fifth Line
</pre></div>
</td></tr></tbody></table></div><span id="the-else-and-finally-clause" class="anchor-target"></span><h2 class="heading">The else and finally clause <a class="header-link" href="#the-else-and-finally-clause">#</a></h2>

<p>A <code>try-except</code> statement can also have an optional <code>else</code> clause which only gets executed when no exception is raised. The general format of <code>try-except</code> statement with <code>else</code> clause is as follows:</p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>    
    <span class="o">&lt;</span><span class="n">statement_1</span><span class="o">&gt;</span>
    <span class="o">&lt;</span><span class="n">statement_2</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="o">&lt;</span><span class="n">ExceptiomType1</span><span class="o">&gt;</span><span class="p">:</span>    
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="o">&lt;</span><span class="n">ExceptiomType2</span><span class="o">&gt;</span><span class="p">:</span>    
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
<span class="k">else</span><span class="p">:</span>
    <span class="c1"># else block only gets executed</span>
    <span class="c1"># when no exception is raised in the try block</span>
    <span class="o">&lt;</span><span class="n">statement</span><span class="o">&gt;</span>
    <span class="o">&lt;</span><span class="n">statement</span><span class="o">&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p>Here is a rewrite of the above program using the <code>else</code> clause.</p>

<p><strong>python101/Chapter-19/else_clause_demo.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">os</span>
<span class="n">filename</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">&#34;Enter file name: &#34;</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="n">filename</span><span class="p">,</span> <span class="s2">&#34;r&#34;</span><span class="p">)</span>

    <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">f</span><span class="p">:</span>
        <span class="k">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="s2">&#34;&#34;</span><span class="p">)</span>

    <span class="n">f</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>

<span class="k">except</span> <span class="n">FileNotFoundError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;File not found&#34;</span><span class="p">)</span>

<span class="k">except</span> <span class="n">PermissionError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;You don&#39;t have the permission to read the file&#34;</span><span class="p">)</span>

<span class="k">except</span> <span class="n">FileExistsError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;You don&#39;t have the permission to read the file&#34;</span><span class="p">)</span>

<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Unexpected error while reading the file&#34;</span><span class="p">)</span>

<span class="k">else</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Program ran without any problem&#34;</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/28J/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p>Run the program and enter a file that doesn&#39;t exist.</p>

<p><strong>First run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter file name: terraform.txt
File not found
</pre></div>
</td></tr></tbody></table></div>
<p>Again run the program but this time enter a file that does exist and you have the permission to access it.</p>

<p><strong>Second run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter file name: ../Chapter-18/readme.md
First Line
Second Line
Third Line
Fourth Line
Fifth Line
Program ran without any problem
</pre></div>
</td></tr></tbody></table></div>
<p>As expected, the statement in the <code>else</code> clause is executed this time. The <code>else</code> clause is usually used to write code which we want to run after the code in the try block ran successfully.</p>

<p>Similarly, we can have a <code>finally</code> clause after all <code>except</code> clauses. The statements under the <code>finally</code> clause will always execute irrespective of whether the exception is raised or not. It&#39;s general form is as follows:</p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>    
    <span class="o">&lt;</span><span class="n">statement_1</span><span class="o">&gt;</span>
    <span class="o">&lt;</span><span class="n">statement_2</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="o">&lt;</span><span class="n">ExceptiomType1</span><span class="o">&gt;</span><span class="p">:</span>    
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
<span class="k">except</span> <span class="o">&lt;</span><span class="n">ExceptiomType2</span><span class="o">&gt;</span><span class="p">:</span>    
    <span class="o">&lt;</span><span class="n">handler</span><span class="o">&gt;</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="c1"># statements here will always</span>
    <span class="c1"># execute no matter what</span>
    <span class="o">&lt;</span><span class="n">statement</span><span class="o">&gt;</span>
    <span class="o">&lt;</span><span class="n">statement</span><span class="o">&gt;</span>
</pre></div>
</td></tr></tbody></table></div>
<p>The <code>finally</code> clause is commonly used to define clean up actions that must be performed under any circumstance. If the <code>try-except</code> statement has an <code>else</code> clause then the <code>finally</code> clause must appear after it.</p>

<p>The following program shows the <code>finally</code> clause in action.</p>

<p><strong>python101/Chapter-19/finally_clause_demo.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">os</span>
<span class="n">filename</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">&#34;Enter file name: &#34;</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="n">filename</span><span class="p">,</span> <span class="s2">&#34;r&#34;</span><span class="p">)</span>

    <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">f</span><span class="p">:</span>
        <span class="k">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="s2">&#34;&#34;</span><span class="p">)</span>

    <span class="n">f</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>

<span class="k">except</span> <span class="n">FileNotFoundError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;File not found&#34;</span><span class="p">)</span>

<span class="k">except</span> <span class="n">PermissionError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;You don&#39;t have the permission to read the file&#34;</span><span class="p">)</span>

<span class="k">except</span> <span class="n">FileExistsError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;You don&#39;t have the permission to read the file&#34;</span><span class="p">)</span>

<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Unexpected error while reading the file&#34;</span><span class="p">)</span>

<span class="k">else</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;</span><span class="se">\n</span><span class="s2">Program ran without any problem&#34;</span><span class="p">)</span>

<span class="k">finally</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;finally clause: This will always execute&#34;</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/36r/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>First run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter file name: little.txt
File not found
finally clause: This will always execute
</pre></div>
</td></tr></tbody></table></div>
<p><strong>Second run output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7
8</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Enter file name: readme.md
First Line
Second Line
Third Line
Fourth Line
Fifth Line
Program ran without any problem
finally clause: This will always execute
</pre></div>
</td></tr></tbody></table></div><span id="exceptions-propagation-and-raising-exceptions" class="anchor-target"></span><h2 class="heading">Exceptions Propagation and Raising Exceptions <a class="header-link" href="#exceptions-propagation-and-raising-exceptions">#</a></h2>

<p>In the earlier few sections, we have learned how to deal with exceptions using the <code>try-except</code> statement. In this section, we will discuss who throws an exception, how to create an exception and how they propagate.</p>

<p>An exception is simply an object raised by a function signaling that something unexpected has happened which the function itself can&#39;t handle. A function raises exception by creating an exception object from an appropriate class and then throws the exception to the calling code using the <code>raise</code> keyword as follows:</p>
<div class="codeblock language-python"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="n">SomeExceptionClas</span><span class="p">(</span><span class="s2">&#34;Error message describing cause of the error&#34;</span><span class="p">)</span>
</pre></div>
</div>
<p>We can raise exceptions from our own functions by creating an instance of <code>RuntimeError()</code> as follows:</p>
<div class="codeblock language-python"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&#34;Someting went very wrong&#34;</span><span class="p">)</span>
</pre></div>
</div>
<p>When an exception is raised inside a function and is not caught there, it is automatically propagated to the calling function (and any function up in the stack), until it is caught by <code>try-except</code> statement in some calling function. If the exception reaches the main module and still not handled, the program terminates with an error message.</p>

<p>Let&#39;s take an example.</p>

<p>Suppose we are creating a function to calculate factorial of a number. As factorial is only valid for positive integers, passing data of any other type would render the function useless. We can prevent this by checking the type of argument and raising an exception if the argument is not a positive integer. Here is the complete code.</p>

<p><strong>python101/Chapter-19/factorial.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">factorial</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
    <span class="k">if</span>  <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">n</span><span class="p">,</span> <span class="nb">int</span><span class="p">):</span>
        <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&#34;Argument must be int&#34;</span><span class="p">)</span>

    <span class="k">if</span> <span class="n">n</span> <span class="o">&lt;</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&#34;Argument must be &gt;= 0&#34;</span><span class="p">)</span>

    <span class="n">f</span> <span class="o">=</span> <span class="mi">1</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
        <span class="n">f</span> <span class="o">*=</span> <span class="n">n</span>
        <span class="n">n</span> <span class="o">-=</span> <span class="mi">1</span>

    <span class="k">return</span> <span class="n">f</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 4 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="mi">4</span><span class="p">))</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 12 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="s2">&#34;12&#34;</span><span class="p">))</span>
<span class="k">except</span> <span class="ne">RuntimeError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Invalid Input&#34;</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/462/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>Output:</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="n">Factorial</span> <span class="n">of</span> <span class="mi">4</span> <span class="ow">is</span><span class="p">:</span> <span class="mi">24</span>
<span class="n">Invalid</span> <span class="n">Input</span>
</pre></div>
</td></tr></tbody></table></div>
<p>Notice that when the <code>factorial()</code> function is called with a string argument (line 17), a runtime exception is raised in line 3. As <code>factorial()</code> function is not handling the exception, the raised exception is propagated back to the <code>main</code> module where it is caught by the <code>except</code> clause in line 18.</p>

<p>Note that in the above example we have coded the <code>try-except</code> statement outside the <code>factorial()</code> function but we could have easily done the same inside the <code>factorial()</code> function as follows.</p>

<p><strong>python101/Chapter-19/handling_exception_inside_factorial_func.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">factorial</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>

    <span class="k">try</span><span class="p">:</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">n</span><span class="p">,</span> <span class="nb">int</span><span class="p">):</span>
            <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&#34;Argument must be int&#34;</span><span class="p">)</span>

        <span class="k">if</span> <span class="n">n</span> <span class="o">&lt;</span> <span class="mi">0</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&#34;Argument must be &gt;= 0&#34;</span><span class="p">)</span>

        <span class="n">f</span> <span class="o">=</span> <span class="mi">1</span>
        <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
            <span class="n">f</span> <span class="o">*=</span> <span class="n">n</span>
            <span class="n">n</span> <span class="o">-=</span> <span class="mi">1</span>

        <span class="k">return</span> <span class="n">f</span>

    <span class="k">except</span> <span class="ne">RuntimeError</span><span class="p">:</span>
        <span class="k">return</span>  <span class="s2">&#34;Invalid Input&#34;</span>

<span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 4 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="mi">4</span><span class="p">))</span>
<span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 12 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="s2">&#34;12&#34;</span><span class="p">))</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/57x/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>Output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Factorial of 4 is: 24
Factorial of 12 is: Invalid Input
</pre></div>
</td></tr></tbody></table></div>
<p>However, this is not recommended. Generally, the called function throws an exception to the caller and it&#39;s the duty of the calling code to handle the exception. This approach allows us to to handle exceptions in different ways, for example, in one case we show an error message to the user while in other we silently log the problem. If we were handling exceptions in the called function, then we would have to update the function every time a new behavior is required. In addition to that, all the functions in the Python standard library also conforms to this behavior. The library function only detects the problem and raises an exception and the client decide what it needs to be done to handle those errors.</p>

<p>Now Let&#39;s see what happens when an exception is raised in a deeply nested function call. Recall that if an exception is raised inside the function and is not caught by the function itself, it is passed to its caller. This process repeats until it is caught by some calling function down in the stack. Consider the following example.</p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">function3</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>

        <span class="o">...</span>
        <span class="k">raise</span> <span class="n">SomeException</span><span class="p">()</span>
    <span class="n">statement7</span>
    <span class="k">except</span> <span class="n">ExceptionType4</span><span class="p">:</span>
        <span class="n">handler</span>
    <span class="n">statement8</span>


<span class="k">def</span> <span class="nf">function2</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="o">...</span>
        <span class="n">function3</span><span class="p">()</span>
        <span class="n">statement5</span>
    <span class="k">except</span> <span class="n">ExceptionType3</span><span class="p">:</span>
        <span class="n">handler</span>
    <span class="n">statement6</span>

<span class="k">def</span> <span class="nf">function1</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="o">...</span>
        <span class="n">function2</span><span class="p">()</span>
        <span class="n">statement3</span>
    <span class="k">except</span> <span class="n">ExceptionType2</span><span class="p">:</span>
        <span class="n">handler</span>
    <span class="n">statement4</span>

<span class="k">def</span> <span class="nf">main</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="o">...</span>
        <span class="n">function1</span><span class="p">()</span>
        <span class="n">statement1</span>
    <span class="k">except</span> <span class="n">ExceptionType1</span><span class="p">:</span>
        <span class="n">handler</span>
     <span class="n">statement2</span>
    
<span class="n">main</span><span class="p">()</span>
</pre></div>
</td></tr></tbody></table></div>
<p>The program execution starts by calling the <code>main()</code> function. The <code>main()</code> function then invokes <code>function1()</code>, <code>function1()</code> invokes <code>function2()</code>, finally <code>function2()</code> invokes <code>function3()</code>. Let&#39;s assume <code>function3()</code> can raise different types of exceptions. Now consider the following cases.</p>

<ol>
<li><p>If the exception is of type <code>ExceptionType4</code>, <code>statement7</code> is skipped and the <code>except</code> clause in line 7 catches it. The execution of <code>function3()</code> proceeds as usual and <code>statement8</code> is executed.</p></li>
<li><p>If exception is of type <code>ExceptionType3</code>, the execution of <code>function3()</code> is aborted (as there is no matching <code>except</code> clause to handle the raised exception) and the control is transferred to the caller i.e <code>function2()</code> where <code>ExceptionType3</code> is handled by the <code>except</code> clause in line 17. The <code>statement5</code> in <code>function2()</code> is skipped and <code>statement6</code> is executed.</p></li>
<li><p>If the exception is of type <code>ExceptionType2</code>, <code>function3()</code> is aborted and the control is transferred to the <code>function2()</code>. As <code>function2()</code> doesn&#39;t have any matching <code>except</code> clause to catch the exception, its execution is aborted and control transferred to the <code>function1()</code> where the exception is caught by the <code>except</code> clause in line 26. The <code>statement3</code> in <code>function1()</code>  is skipped and <code>statement4</code> is executed.</p></li>
<li><p>If the exception is of type <code>ExceptionType1</code>, then control is transferred to the function <code>main()</code> (as <code>function3()</code>, <code>function2()</code> and <code>function1()</code> doesn&#39;t have matching <code>except</code> clause to handle the exception) where the exception is handled by <code>except</code> clause in line 35. The <code>statement1</code> in <code>main()</code> is skipped and <code>statement2</code> is executed.</p></li>
<li><p>If the exception is of type <code>ExceptionType0</code>. As none of the available functions have the ability to handle this exception, the program terminates with an error message.</p></li>
</ol>
<span id="accessing-exception-object" class="anchor-target"></span><h2 class="heading">Accessing Exception Object <a class="header-link" href="#accessing-exception-object">#</a></h2>

<p>Now we know how to handle exceptions as well throw them whenever needed. One thing we didn&#39;t yet cover is how to access exception object thrown by the function. We can access exception object using the following form of except clause.</p>
<div class="codeblock language-python"><div class="highlight"><pre><span></span><span class="k">except</span> <span class="n">ExceptionType</span> <span class="k">as</span> <span class="n">e</span>
</pre></div>
</div>
<p>From now on, whenever <code>except</code> clause catches an exception of type <code>ExceptionType</code> it assigns the exception object to the variable <code>e</code>.</p>

<p>The following example demonstrates how to access an exception object:</p>

<p><strong>python101/Chapter-19/accessing_exception_object.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">factorial</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">n</span><span class="p">,</span> <span class="nb">int</span><span class="p">):</span>
        <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&#34;Argument must be int&#34;</span><span class="p">)</span>

    <span class="k">if</span> <span class="n">n</span> <span class="o">&lt;</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s2">&#34;Argument must be &gt;= 0&#34;</span><span class="p">)</span>

    <span class="n">f</span> <span class="o">=</span> <span class="mi">1</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
        <span class="n">f</span> <span class="o">*=</span> <span class="n">n</span>
        <span class="n">n</span> <span class="o">-=</span> <span class="mi">1</span>

    <span class="k">return</span> <span class="n">f</span>


<span class="k">try</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 4 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="mi">4</span><span class="p">))</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 12 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="s2">&#34;12&#34;</span><span class="p">))</span>

<span class="k">except</span> <span class="ne">RuntimeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Error:&#34;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/6W7/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>Output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Factorial of 4 is: 24
Error: Argument must be int
</pre></div>
</td></tr></tbody></table></div>
<p>Notice that the error message printed by exception object (line 21) is the same which we passed while creating creating <code>RuntimeError</code> object (line 3).</p>
<span id="creating-your-own-exceptions" class="anchor-target"></span><h2 class="heading">Creating Your Own Exceptions <a class="header-link" href="#creating-your-own-exceptions">#</a></h2>

<p>So far in this chapter we have been using built-it exception classes such as <code>ZeroDivisionError</code>, <code>ValueError</code>, <code>TypeError</code>, <code>RuntimeError</code> etc. Python also allows you to create new exception classes to cater you own specific needs. The <code>BaseException</code> class is the root of all exception classes in Python. The following figure shows exception class hierarchy in Python.</p>

<p><img src="../../media/uploads/2017/09/28/exception-class-hierarchy.png" loading="lazy" alt=""/></p>

<p>We can create our own exception class by deriving it from <code>Exception</code> built-in class. The following examples shows how to create a custom exception.</p>

<p><strong>python101/Chapter-19/InvalidFactorialArgumentException.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2
3
4
5
6
7</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">InvalidFactorialArgumentException</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">message</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__init__</span><span class="p">()</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">message</span> <span class="o">=</span> <span class="n">message</span>

    <span class="k">def</span> <span class="fm">__str__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">message</span>
</pre></div>
</td></tr></tbody></table></div>
<p><strong>python101/Chapter-19/factorialWithCustomException.py</strong></p>
<div class="codeblock language-python"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23</pre></div></td><td class="code"><div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">InvalidFactorialArgumentException</span> <span class="kn">import</span> <span class="o">*</span>

<span class="k">def</span> <span class="nf">factorial</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="nb">isinstance</span><span class="p">(</span><span class="n">n</span><span class="p">,</span> <span class="nb">int</span><span class="p">):</span>
        <span class="k">raise</span> <span class="n">InvalidFactorialArgumentException</span><span class="p">(</span><span class="s2">&#34;Argument must be int&#34;</span><span class="p">)</span>

    <span class="k">if</span> <span class="n">n</span> <span class="o">&lt;</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">raise</span> <span class="n">InvalidFactorialArgumentException</span><span class="p">(</span><span class="s2">&#34;Argument must be &gt;= 0&#34;</span><span class="p">)</span>

    <span class="n">f</span> <span class="o">=</span> <span class="mi">1</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">n</span><span class="p">):</span>
        <span class="n">f</span> <span class="o">*=</span> <span class="n">n</span>
        <span class="n">n</span> <span class="o">-=</span> <span class="mi">1</span>

    <span class="k">return</span> <span class="n">f</span>


<span class="k">try</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 4 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="mi">4</span><span class="p">))</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Factorial of 12 is:&#34;</span><span class="p">,</span> <span class="n">factorial</span><span class="p">(</span><span class="s2">&#34;12&#34;</span><span class="p">))</span>

<span class="k">except</span> <span class="n">InvalidFactorialArgumentException</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">&#34;Error:&#34;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
</pre></div>
</td></tr></tbody></table></div>
<p><a href="../../python-online-compiler/79w/index.html" class="btn btn-primary" target="_blank">Try it now</a></p>

<p><strong>Output:</strong></p>
<div class="codeblock language-text"><table class="highlighttable"><tbody><tr><td class="linenos"><div class="linenodiv"><pre>1
2</pre></div></td><td class="code"><div class="highlight"><pre><span></span>Factorial of 4 is: 24
Error: Argument must be int
</pre></div>
</td></tr></tbody></table></div>


    



        <nav aria-label="pagination">
            <ul class="pager">
                
                    <li class="previous">
                        <a href="../file-handling-in-python/index.html" title="File Handling in Python">
                            <span class="fa fa-arrow-left" aria-hidden="true"></span>
                            File Handling in Python
                        </a>
                    </li>
                

                
                    <li class="next">
                        <a href="../tuples-in-python/index.html" title="Tuples in Python">
                            Tuples in Python
                            <span class="fa fa-arrow-right" aria-hidden="true"></span>
                        </a>
                    </li>
                
            </ul>
        </nav>







    <hr/>
    <div id="disqus_thread">
    <p style="margin-bottom: 10px" class="text-center">
        <a href="#" class=" btn btn-primary comments-holder" onclick="loadDisqus();return false;">
            <i class="fa fa-comments" aria-hidden="true"></i> Load Comments
        </a>
    </p>
    </div>
    <hr/>
    <script>
        var is_disqus_loaded = false;
        function loadDisqus() { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = '../../../overiqcom.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        };
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>







            </div>
        </div>


        <div class="sidebar">
        
            <div class="col-lg-4 col-md-4 col-sm-12">
                

    
        
    <div class="well">
        <h4>Python Tutorial</h4>
        <ul>
            
                <li><a href="../intro-to-python/index.html">Intro to Python</a></li>
            
                <li><a href="../installing-python/index.html">Installing Python</a></li>
            
                <li><a href="../idle-and-python-shell/index.html">IDLE and Python Shell</a></li>
            
                <li><a href="../data-types-and-variables-in-python/index.html">Data Types and Variables In Python</a></li>
            
                <li><a href="../numbers-in-python/index.html">Numbers in Python</a></li>
            
                <li><a href="../operators-in-python/index.html">Operators in Python</a></li>
            
                <li><a href="../strings-in-python/index.html">Strings in Python</a></li>
            
                <li><a href="../strings-methods-in-python/index.html">Strings Methods in Python</a></li>
            
                <li><a href="../if-else-statements-in-python/index.html">If-else statements in Python</a></li>
            
                <li><a href="../loops-in-python/index.html">Loops in Python</a></li>
            
                <li><a href="../break-and-continue-statement-in-python/index.html">break and continue statement in Python</a></li>
            
                <li><a href="../lists-in-python/index.html">Lists in Python</a></li>
            
                <li><a href="../functions-in-python/index.html">Functions in Python</a></li>
            
                <li><a href="../modules-in-python/index.html">Modules in Python</a></li>
            
                <li><a href="../objects-and-classes-in-python/index.html">Objects and Classes in Python</a></li>
            
                <li><a href="../inheritance-and-polymorphism-in-python/index.html">Inheritance and Polymorphism in Python</a></li>
            
                <li><a href="../operator-overloading-in-python/index.html">Operator Overloading in Python</a></li>
            
                <li><a href="../file-handling-in-python/index.html">File Handling in Python</a></li>
            
                <li><a href="index.html">Exception Handling in Python</a></li>
            
                <li><a href="../tuples-in-python/index.html">Tuples in Python</a></li>
            
                <li><a href="../sets-in-python/index.html">Sets in Python</a></li>
            
                <li><a href="../dictionary-in-python/index.html">Dictionary in Python</a></li>
            
        </ul>
    </div>

    

    
        

<div class="well">
    <h4>Recent Posts</h4>
    <ul>
        
            <li><a href="../../machine-learning-experts-you-should-be-following-online/index.html">Machine Learning Experts You Should Be Following Online</a></li>
        
            <li><a href="../../4-ways-to-prepare-for-the-ap-computer-science-a-exam/index.html">4 Ways to Prepare for the AP Computer Science A Exam</a></li>
        
            <li><a href="../../finance-assignment-online-help-for-the-busy-and-tired-students-get-help-from-experts/index.html">Finance Assignment Online Help for the Busy and Tired Students: Get Help from Experts</a></li>
        
            <li><a href="../../top-9-machine-learning-algorithms-for-data-scientists/index.html">Top 9 Machine Learning Algorithms for Data Scientists</a></li>
        
            <li><a href="../../data-science-learning-path-or-steps-to-become-a-data-scientist-final/index.html">Data Science Learning Path or Steps to become a data scientist Final</a></li>
        
            <li><a href="../../enable-edit-button-in-shutter-in-linux-mint-19-and-ubuntu-18-04/index.html">Enable Edit Button in Shutter In Linux Mint 19 and Ubuntu 18.04</a></li>
        
            <li><a href="../../python-3-time-module/index.html">Python 3 time module</a></li>
        
            <li><a href="../../pygments-tutorial/index.html">Pygments Tutorial</a></li>
        
            <li><a href="../../how-to-use-virtualenv/index.html">How to use Virtualenv?</a></li>
        
            <li><a href="../../installing-mysql-windows-linux-and-mac/index.html">Installing MySQL (Windows, Linux and Mac)</a></li>
        
            <li><a href="../../what-is-if-__name__-__main__-in-python/index.html">What is if __name__ == &#39;__main__&#39;  in Python ?</a></li>
        
            <li><a href="../../installing-goaccess-a-real-time-web-log-analyzer/index.html">Installing GoAccess (A Real-time web log analyzer)</a></li>
        
            <li><a href="../../installing-isso/index.html">Installing Isso</a></li>
        
    </ul>
</div>

<!-- Blog Search Well -->





















    



            </div>
        </div>
    </div>



    

</div>

<!-- Footer -->
<footer class="overiq-footer">
    <div class="container">
        <div class="row">

            <div class="col-lg-3 col-md-3 col-sm-6 overiq-footer-links">
                <ul>
                    <li><a href="../../index.html">Home</a></li>
                    <li><a href="../../terms-of-use/index.html">Terms</a></li>
                    <li><a href="../../privacy-policy/index.html">Privacy Policy</a></li>
                    <li><a href="../../sitemap.xml/index.html">Sitemap</a></li>
                </ul>

            </div>

            <div class="col-lg-3 col-md-3 col-sm-6 overiq-footer-links">
                <ul>
                    <li><a href="../../contact/index.html">Contact</a></li>
                    <li><a href="../../blog/index.html">Blog</a></li>
                </ul>

            </div>

            <div class="col-lg-3 col-md-3 col-sm-6 overiq-footer-links">
                <ul>
                    <li><a href="https://www.facebook.com/OverIQ/">Facebook</a></li>
                    <li><a href="https://twitter.com/infoOverIQ">Twitter</a></li>
                    <li><a href="https://github.com/overiq">Github</a></li>
                </ul>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-6 overiq-footer-links">
                <ul>
                    <li><a href="../../c-programming-101/index.html">C Tutorial</a></li>
                    <li><a href="../index.html">Python Tutorial</a></li>
                    <li><a href="../../django-1-11/index.html">Django Tutorial</a></li>
                    <li><a href="../../flask-101/index.html">Flask Tutorial</a></li>
                    <li><a href="../../mysql-connector-python-101/index.html">MySQL Connector/Python Tutorial</a></li>
                    <li><a href="../../sqlalchemy-101/index.html">SQLAlchemy Tutorial</a></li>
                    <li><a href="../../c-examples/index.html">C Programming Examples</a></li>
                </ul>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row text-center">
            <p>© 2025 OverIQ.com</p>
            <small><a href="#">Back to top</a></small>
        </div>

        <!-- /.row -->
    </div>
</footer>



<script type="text/javascript" src="../../static/CACHE/js/output.2e0ff002c1a4.js"></script>




<script async="" src="../../../cdn.jsdelivr.net/npm/cookieconsent%403/build/cookieconsent.min.js" data-cfasync="false"></script>

<script>

    
    window.addEventListener('load', function () {
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "#5ca9e0",
                    "text": "#ffffff"
                },
                "button": {
                    "background": "#fff",
                    "text": "#237afc"
                }
            },
            "theme": "classic",
            "position": "top",
            "static": true,
            "content": {
                "href": "https://overiq.com/privacy-policy/"
            }
        });
    });


</script>

<script src="../../../polyfill.io/v3/polyfill.min1162.js?features=es6"></script>
<script id="MathJax-script" defer="" src="../../../cdn.jsdelivr.net/npm/mathjax%403/es5/tex-chtml.js"></script>

<script async="" type="text/javascript" src="../../../cdn.carbonads.com/carbonfbdb.js?serve=CE7DC53E&amp;placement=overiqcom" id="_carbonads_js"></script>





<script data-cfasync="false">function _emitEzConsentEvent(){var customEvent=new CustomEvent("ezConsentEvent",{detail:{ezTcfConsent:window.ezTcfConsent},bubbles:true,cancelable:true,});document.dispatchEvent(customEvent);}
(function(window,document){function _setAllEzConsentTrue(){window.ezTcfConsent.loaded=true;window.ezTcfConsent.store_info=true;window.ezTcfConsent.develop_and_improve_services=true;window.ezTcfConsent.measure_ad_performance=true;window.ezTcfConsent.measure_content_performance=true;window.ezTcfConsent.select_basic_ads=true;window.ezTcfConsent.create_ad_profile=true;window.ezTcfConsent.select_personalized_ads=true;window.ezTcfConsent.create_content_profile=true;window.ezTcfConsent.select_personalized_content=true;window.ezTcfConsent.understand_audiences=true;window.ezTcfConsent.use_limited_data_to_select_content=true;window.ezTcfConsent.select_personalized_content=true;}
function _clearEzConsentCookie(){document.cookie="ezCMPCookieConsent=tcf2;Domain=.overiq.com;Path=/;expires=Thu, 01 Jan 1970 00:00:00 GMT";}
_clearEzConsentCookie();if(typeof window.__tcfapi!=="undefined"){window.ezgconsent=false;var amazonHasRun=false;function _ezAllowed(tcdata,purpose){return(tcdata.purpose.consents[purpose]||tcdata.purpose.legitimateInterests[purpose]);}
function _handleConsentDecision(tcdata){window.ezTcfConsent.loaded=true;if(!tcdata.vendor.consents["347"]&&!tcdata.vendor.legitimateInterests["347"]){window._emitEzConsentEvent();return;}
window.ezTcfConsent.store_info=_ezAllowed(tcdata,"1");window.ezTcfConsent.develop_and_improve_services=_ezAllowed(tcdata,"10");window.ezTcfConsent.measure_content_performance=_ezAllowed(tcdata,"8");window.ezTcfConsent.select_basic_ads=_ezAllowed(tcdata,"2");window.ezTcfConsent.create_ad_profile=_ezAllowed(tcdata,"3");window.ezTcfConsent.select_personalized_ads=_ezAllowed(tcdata,"4");window.ezTcfConsent.create_content_profile=_ezAllowed(tcdata,"5");window.ezTcfConsent.measure_ad_performance=_ezAllowed(tcdata,"7");window.ezTcfConsent.use_limited_data_to_select_content=_ezAllowed(tcdata,"11");window.ezTcfConsent.select_personalized_content=_ezAllowed(tcdata,"6");window.ezTcfConsent.understand_audiences=_ezAllowed(tcdata,"9");window._emitEzConsentEvent();}
function _handleGoogleConsentV2(tcdata){if(!tcdata||!tcdata.purpose||!tcdata.purpose.consents){return;}
var googConsentV2={};if(tcdata.purpose.consents[1]){googConsentV2.ad_storage='granted';googConsentV2.analytics_storage='granted';}
if(tcdata.purpose.consents[3]&&tcdata.purpose.consents[4]){googConsentV2.ad_personalization='granted';}
if(tcdata.purpose.consents[1]&&tcdata.purpose.consents[7]){googConsentV2.ad_user_data='granted';}
if(googConsentV2.analytics_storage=='denied'){gtag('set','url_passthrough',true);}
gtag('consent','update',googConsentV2);}
__tcfapi("addEventListener",2,function(tcdata,success){if(!success||!tcdata){window._emitEzConsentEvent();return;}
if(!tcdata.gdprApplies){_setAllEzConsentTrue();window._emitEzConsentEvent();return;}
if(tcdata.eventStatus==="useractioncomplete"||tcdata.eventStatus==="tcloaded"){if(typeof gtag!='undefined'){_handleGoogleConsentV2(tcdata);}
_handleConsentDecision(tcdata);if(tcdata.purpose.consents["1"]===true&&tcdata.vendor.consents["755"]!==false){window.ezgconsent=true;(adsbygoogle=window.adsbygoogle||[]).pauseAdRequests=0;}
if(window.__ezconsent){__ezconsent.setEzoicConsentSettings(ezConsentCategories);}
__tcfapi("removeEventListener",2,function(success){return null;},tcdata.listenerId);if(!(tcdata.purpose.consents["1"]===true&&_ezAllowed(tcdata,"2")&&_ezAllowed(tcdata,"3")&&_ezAllowed(tcdata,"4"))){if(typeof __ez=="object"&&typeof __ez.bit=="object"&&typeof window["_ezaq"]=="object"&&typeof window["_ezaq"]["page_view_id"]=="string"){__ez.bit.Add(window["_ezaq"]["page_view_id"],[new __ezDotData("non_personalized_ads",true),]);}}}});}else{_setAllEzConsentTrue();window._emitEzConsentEvent();}})(window,document);</script></body>
<!-- Mirrored from overiq.com/python-101/exception-handling-in-python/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 01 Feb 2025 11:09:07 GMT -->
</html>